# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
guava = "33.4.6-jre"
junit-jupiter = "5.12.1"
publish-to-maven = "0.35.0"
jakarta-persistence = "3.2.0"
jackson = "2.20.1"
jdbc-version = "7.0.2"
spring-resilience = "5.0.0"
mockito-core = "5.21.0"
mockito-junit-jupiter = "5.21.0"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
jakarta-persistence = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakarta-persistence" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jdbc = { module = "org.springframework:spring-jdbc", version.ref = "jdbc-version" }
spring-resilience = { module = "org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j", version.ref = "spring-resilience" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito-junit-jupiter" }

[plugins]
publish-to-maven = { id = "com.vanniktech.maven.publish", version.ref = "publish-to-maven" }
